### ISSUE TITLE
Crash when fetching packages while "Daily (archive)" is included

### ISSUE THREAD

**Issue by hcraT** [AlexChaplinBraz/BlenderLauncher#3]
Hi,
first of all thanks for the package. Is very cool.

As per the subject if the "Daily (archive)" is included among the build types I get a crash with the following error message.
```
$ RUST_BACKTRACE=1 ablavema 
Not the time to check for updates yet.
thread 'main' panicked at 'internal error: entered unreachable code: mismatched build types', src/package.rs:250:22
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace
```
I've tried also using RUST_BACKTRACE=full but I only obtain a list of memory addresses with no source code annotations (I suppose that my rust installation is not built with debug information).

If I remove the file file that contains the db (i.e. `.config/ablavema/daily_archive.bin`) the app starts correctly again.

I'm running version `0.3.0` on arch linux that was installed via AUR.

**Comment by hcraT** [comment]
I don't know rust but I see that you made a change exactly where the error happens. So I suppose that you were already aware of this issue. If so, sorry for the noise.

**Comment by AlexChaplinBraz** [comment]
Yeah, sorry for not releasing an update after I fixed that crash. I was planning to add at least one feature so it's not just a crash fix release, but then life happened and, apart from that, I started another project completely unrelated to programming, so I kinda let Ablavema slip out of my mind.

Tell you what, since I already waited too long, I might as well wait a little bit more and add that feature I wanted to add. I'll try to add a "Recent files" tab in the coming week, so you can look forward to that. Can't really be called a "launcher" without the ability to do that.
