### ISSUE TITLE
memory allocation of 8028843017030165864 bytes failed

### ISSUE THREAD

**Issue by matheusfillipe** [AlexChaplinBraz/BlenderLauncher#5]
I tried both installing with `cargo install ablavema` and using the package from AUR. It doesn't launch:
```
$ ablavema
memory allocation of 8028843017030165864 bytes failed
[1]    1348504 abort (core dumped)  ablavema

```
That's quite a lot of memory it is trying to alocate :P

**Comment by AlexChaplinBraz** [comment]
Sorry for the late reply. I read the email on my phone but only just now got back home and have access to my computer.

Anyway, from what I remember, this is an issue where `serde` fails to deserialize a file because the struct has changed. The simple solution is to delete the entire configuration directory.

I thought I handled all the cases where this may happen, but I guess I missed something. I'll investigate this next year.

**Comment by matheusfillipe** [comment]
Ok, after deleting `.config/ablavema` it launches but then i get:
`Failed to connect to server and check for updates.`
![image](https://user-images.githubusercontent.com/24435787/147613477-e63e9051-ff84-40c5-a899-f68d6674f64b.png)

Is that related? Should i open a new issue?

**Comment by AlexChaplinBraz** [comment]
When it shows that, it's because it literally cannot get info from the pages that the program uses to download releases. This could be because your internet is down, one of the pages is down, or maybe you've been refreshing too often and got temporarily banned (you'll be unbanned within an hour from what I've experienced).

There's also a known bug where it gives a false negative randomly and will be resolved right away if you click on the `[R]`, though I think it's not a problem on my end because I've had that particular page randomly fail to load in browsers as well.

I tried just now and it works for me, so try again and tell me how it goes. I've only had it happen in the situations I described. Most often it's resolved by just retrying right away.

**Comment by AlexChaplinBraz** [comment]
As an aside, I see that the text in the sidebar is wrapped. I've seen another person's screenshot show the same, even though it looks just fine on my machines. I'll add a TODO to expand it a bit so it looks like mine.

![image](https://user-images.githubusercontent.com/45469201/147614005-621fe1b0-a4a4-416b-9a67-d5638af0cf11.png)

Although, from what I see in your screenshot, I'd have to expand that way too much for the `Experimental (something)` to fit in one line. I should probably instead shorten all of the text in parenthesis into a single letter and add tooltips.

Almost makes me want to just bake in a font and use that so it's always the same... Though I wonder if this is something to do with scaling instead? Requires further investigation.
